/*
* DO NOT MODIFY THIS COMMENT
* Generated by devmate
* Test model: d4114011-8ccd-41c2-87d1-cb1033738b93
*/

namespace HelloWorld.Tests
{
	using System;
	using System.Collections.Generic;
	using NUnit.Framework;

	public class GreetTestCase
	{
		private static IEnumerable<TestCaseData> PositiveTests()
		{
			yield return new TestCaseData("World", "Hello World")
				.SetName("p1")
				.SetDescription("");
		}

		[Test]
		[TestCaseSource("PositiveTests")]
		public void GreetTest(String whom, String expected)
		{
			String actual = HelloWorld.Example.Greet(whom);
			Assert.AreEqual(expected, actual);
		}
	}
}

/*
WARNING: Modification of this comment will make it impossible to merge user-defined changes

BEGIN_CODEGEN_DATA
H4sIAAAAAAAAAF2RXUsrMRCGr7Ow/2HYq620q2sL1q8D0lbbi7bCVkTEi2wyaDjZzZ4k21rE/24Sq/YICWSSed+ZZ3J
4EEcHMF7CYrmC+XI8u36A1XRWwGg5n08WK/96gzVqapFDuQWO68qd/f0KjYVKcZRnwAd5PjjK896QMd4b5Oy4NzzheY
+V+VG/f9Iflqd9pzmMoziqaYWmoQxhilKqe6Ulz7yZiaO3OCKtEfUzFFtjsTr/FWcjJSUyK1RtstCYYD85i7ta2Oxau
wIbpf+e+2qkaUspGDBJjYEbjWh9rRE1DoL4eqTRYu2YwFhqXeZsUreVIy4lXnyljqmlf+BWGWHFGkOzacdrgwHZCpQc
NNpW11DjBvZ1aRIQky4kARg+wyAnJCvQLlzDadLk+3djNEyLxpOmSdLxkOQ9AJFH7/70ffJ1CtVq5jz+6zDphKTdANZ
K8B/+tLDaj2zzoqou7AJ8bdxske+R7V4osy2VcLn/ZZNXWjUSs+CZeqPPLsmVMahtdqVx8s+p0i/b7s7mG8Zvtz4ABR
iy+YUCAAA=
END_CODEGEN_DATA
*/
